/**: 
  ros__parameters:
    acceptable_max_delay: 1.0
    gnss_mahalanobis_distance_threshold: 30.0 # If the distance to GNSS observation exceeds this, the correction is skipped.
    use_ublox_msg: false # Raw sensor data should not be used when running as Autoware.
    ignore_less_than_float: false
    for_fixed/max_weight: 5.0

