/**: 
  ros__parameters:
    visualize: true

    static_linear_covariance: 0.25
    static_angular_covariance: 0.001

    resampling_interval_seconds: 1.0
    num_of_particles: 500
    prediction_rate: 50.0

    is_swap_mode: false # developing feature