/**:
  ros__parameters:
    use_sensor_qos: true
    width: 800
    override_frame_id: "" # Value for overriding the camera's frame_id. If blank, frame_id of static_tf is not overwritten


    # graph_node selects a road surface area from around this height
    target_height_ratio: 0.85
    #
    target_candidate_box_width: 15
    # graph_segment_node will pickup additional roadlike areas
    pickup_additional_graph_segment: true
    # used when the pickup_additional_graph_segment: true
    similarity_score_threshold: 0.8
    # parameters for cv::ximgproc::segmentation
    sigma: 0.5
    k: 300.0
    min_size: 100.0


    min_segment_length:  1.5    # if it is negative, it is unlimited
    max_segment_distance:  30.0 # if it is negative, it is unlimited
    max_lateral_distance: 10.0  # if it is negative, it is unlimited
    publish_image_with_segment_for_debug: true
    max_range: 20.0
    image_size: 800 # debug