/**: 
  ros__parameters:

    # =============================================
    # particle filter
    # =============================================
    particle_predictor:
      static_linear_covariance: 0.04
      static_angular_covariance: 0.006
      resampling_interval_seconds: 1.0
      num_of_particles: 500
      prediction_rate: 50.0

    gnss_particle_corrector:
      acceptable_max_delay: 1.0
      gnss_mahalanobis_distance_threshold: 20.0
      use_ublox_msg: true
      ignore_less_than_float: false

    camera_particle_corrector:
      acceptable_max_delay: 1.0
      max_range: 40.0
      gamma: 5.0
      min_prob: 0.1
      far_weight_gain: 0.001
      enabled_at_first: true
      visualize:

    # =============================================
    # pose initalizer
    # =============================================
    particle_initializer:
      cov_xx_yy: [2.0,0.25]

    camera_pose_initializer:
      angle_resolution: 30

    # =============================================
    # map
    # =============================================
    ll2_decomposer:
        road_marking_labels: [cross_walk, zebra_marking, line_thin, line_thick, pedestrian_marking, stop_line, road_border]
        sign_board_labels: [sign-board]
        bounding_box_labels: []

    ground_server:
      force_zero_tilt: false
      K: 50
      R: 10

    # =============================================
    # image processing
    # =============================================


    # =============================================
    # twist estimator
    # =============================================
    twist_estimator:
      stop_vel_threshold: 0.05
      static_scale_factor: -1.0
      static_gyro_bias: 10.0